// 客户分类写死模板
const templateList = [
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '客户编号',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '客户名称',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '客户代码',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '客户类型',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '战略属性标签',
    colunit: '',
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '主题属性标签',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '行业属性标签',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '所属客户经理',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '客户经理所属机构',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '登记机构',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '登记日期',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  },
  {
    colname: 'CustomerID',
    coltype: 'String',
    colheader: '更新日期',
    colunit: null,
    colcolumntype: '1',
    colcheckformat: '字符串',
    colalign: '1',
    coleditstyle: '文本框',
    coleditsourcetype: null,
    coleditsource: null,
    collimit: '32',
    colvisible: '1',
    colreadonly: '1',
    colrequired: '0',
    colcheckitem: '1',
    dockid: 'BasicPart',
    colspan: null
  }
]
