export { default as Text } from './Text.vue'
export { default as Number } from './Number.vue'
export { default as Textarea } from './Textarea.vue'
export { default as Date } from './Date.vue'
export { default as DateTime } from './DateTime.vue'
export { default as Select } from './Select.vue'
export { default as Dict } from './Dict.vue'
export { default as Boolean } from './Boolean.vue'
export { default as Image } from './Image.vue'
export { default as ApiSelect } from './ApiSelect.vue'
export { default as RemoteSelect } from './RemoteSelect.vue'

